server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
       - id: dish
         uri: lb://DISH
         predicates:
           - Path=/api/dish/**
         filters:
           - StripPrefix=2
       - id: credit
         uri: lb://CREDIT
         predicates:
           - Path=/api/credit/**
         filters:
           - StripPrefix=2
       - id: rbac
         uri: lb://RBAC
         predicates:
           - Path=/api/userCrud/**
         filters:
           - StripPrefix=2

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka

